### ISSUE TITLE
How to enter galactic coordinates?

### ISSUE THREAD

**Issue by ojf** [UWMRO/TCC#9]
Docs say we can--but how does it know? Because both are measured in degrees-minutes-seconds?

Answer may lie within "colon delineated RA & Dec broken in Telescope Control tab #8
"

**Comment by dougbrn** [comment]
This can definitely be better addressed as I assimed that this would hardly ever be used, the current way to do it is a bit of a hack. It pops up in the error window if you enter an invalid coordinate format. To do this, you have to put "l=[Value for Galactic Longitude]" in the RA field and "b=[Value for Galactic Latitude]" in the DEC field. It converts this to hh:mm:ss in the background.

**Comment by jwhueh** [comment]
Dougs original point is a good one.  Is this a value that is currently being used?  If so great, but slightly unexpected per the original requirements request.

Joe

**Comment by ojf** [comment]
Looks like we have our answer--will update documentation

**Comment by Ssoyrnoz** [comment]
Documentation has been updated to cover entering galactic coordinates.
